/* eslint-disable import/prefer-default-export */

export enum Routes {
    index = '/',
    home= '/home',
    dashboard= '/dashboard',
    users= '/account/users',
    roles= '/account/roles',
    menu = '/general/menu',
    pages = '/general/pages',
    addPages = '/general/pages/add',
    editPages = '/general/pages/edit',
    sliders = '/general/sliders',
    addSliders = '/general/sliders/add',
    editSliders = '/general/sliders/edit',
    locations = '/general/locations',
    categories = '/general/categories',
    institutions = '/general/institutions',
    contactForms = '/general/contact-forms',
    events = '/events/event',
    eventRequest = '/events/request',
    updateEventRequest = '/events/request/update',
    eventDraft = '/events/draft',
    settings = '/settings',
    socialMedias = '/settings/social-medias',
    qAs = '/settings/qas',
    contracts = '/settings/contracts',
    staticPage = '/settings/static',

    logsUsers= '/logs/users',
    logsRoles= '/logs/roles',
    logsMenu = '/logs/menu',
    logsPages = '/logs/pages',
    logsSliders = '/logs/sliders',
    logsLocations = '/logs/locations',
    logsCategories = '/logs/categories',
    logsInstitutions = '/logs/institutions',
    logsEvents = '/logs/event',
    logsSettings = '/logs/settings',
    logsAccount = '/logs/account',
}
